//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBibliotecaComunitaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.DetallePrestamo = new HashSet<DetallePrestamo>();
        }
    
        public int LibroID { get; set; }
        public string NroDocumento { get; set; }
        public int TipoDocumento { get; set; }
        public string Titulo { get; set; }
        public int Edicion { get; set; }
        public int EditorialID { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public int CantidadEjemplares { get; set; }
        public int CantidadDisponible { get; set; }
    
        public virtual Autor Autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePrestamo> DetallePrestamo { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
